name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn workspace @storipress/unplugin-eta build
      - name: Run test script
        run: yarn workspace unplugin-eta-playground test
